import Navbar from '@component/components/Navbar';
import './globals.css';
import { Poppins } from 'next/font/google';
import Footer from '@component/components/Footer';
import { AuthProvider } from '@component/components/AuthProvider/AuthProvider';
import StateProvider from '@component/components/Context/StateProvider';


const inter = Poppins({ subsets: ['latin'], weight:'400' })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
   
    
        <StateProvider>
        <AuthProvider>
        <Navbar></Navbar>
         <div className='container'>
            {children}
          </div>
        <Footer></Footer>
        </AuthProvider>
        </StateProvider>
       
        
      </body>
    </html>
  )
}
